---
title: '2019-03-20'
author: ""
date: "3/20/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#practice 1:vetor don't need to be numeral
```{r}
bVector<-c("你好","How are you?")
```


#practice 2:the use of single and double quotations
```{r}
dialogue <- c('小明說："明天不用上課。"',
               '小花說："真的嗎？"')

cat(dialogue, sep="\n")



dialogue <- c("小明說：'明天不用上課。'",
               "小花說：'真的嗎？'")

cat(dialogue, sep="\n")
```


#practice 3:logical
```{r}
aLogical <- c(T,TRUE,F,FALSE,FALSE)
class(aLogical)

sum(aLogical) #when calculating logicals, they are treated as 1(true) and 0(false)
```
#practice 4:the meaning of factor
```{r}
studentMajors0 <- c("經濟系", "經濟系", "法律系")
studentMajors <- factor(c("經濟系", "經濟系", "法律系")) #factor allows R to tell the difference between 經濟&法律

class(studentMajors0)
class(studentMajors) 

`studentMajors0` 
`studentMajors`  #you can tell by the output levels that R recognized the difference

```

#practice 5:how does R saves a factor
```{r}
birthplace <- factor(c('台中','台中','台北','台北','台北'))
birthplace
as.integer(birthplace) #as.integer will convert a foctor to a interger(R saves a factor as a integer ), if you want to convert to numeric, use as.numeric
```

```{r}
typeof(studentMajors) 
typeof(studentMajors0)
#typeof() can check what type of data does R saved this object as
 
levels(studentMajors)
 levels(studentMajors0)
 #levels() shows you the levels of a factor
```
#practice 6:
```{r}
stringInteger <- c("1","2","-11")
class(stringInteger) #the quotes cause the supposedly numeric to be recognized as strings thus can't be calculated
```

```{r}
trueInteger <- as.integer(stringInteger)
class(trueInteger) #as.interger converted the numbers in stringinteger and made the calcuable

```

```{r}

```

```{r}

```

